- hosts: databases
  tasks:
    - name: Updates apt cache
      apt: update_cache=true
    - name: Installs necessary packages
      apt: pkg={{ item }} state=latest
      with_items:
        - docker
    - name: Create directory
      file:
	path: /data/mongodb
	state: directory