all:
  hosts:
    instance-1:
  children:
## Nodes for ReplicaSet
    databases:
      hosts:
        mongodb1:
        mongodb2:
        #mongodb3:
        mongodb4:
  vars:
    flush_all: false
    docker_inst: false